name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Configure Maven settings
      run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>hello-world-war</id>
                      <username>supriyasoft16@gmail.com</username>
                      <password>cmVmdGtuOjAxOjE3NjkwNDY0MDI6cFFWdnNHZzZLdVBOT0RpM0xtSWdQeEx4ODUy</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
    - name: Build with Maven
      run: mvn clean deploy
